### PR TITLE
Feature/id 029 stylish checkbox radio

### PR DESCRIPTION
**Pull request by fraed**

### CODE REVIEW

**Comment by MeryemKh** [comment]
The elements checkbox and radio are not responsive.

**Comment by MeryemKh** [comment]
The elements checkbox and radio buttons are not responsive.

**Comment by fraed** [comment]
> after-form-element styling (the red asterisk for required fields) conflicts with the checkmark styling in both radio and checkbox modules which doesn't allow the asterisk to appear.

good catch

**Comment by fraed** [comment]
> The elements checkbox and radio buttons are not responsive.

I think the form is not properly styled at all. Do you think it's ok to open a new issue related to the form styling?

**Comment by fraed** [comment]
To fix: namespace of css vars, eg --width

**Pull request merged**
